# Specific branch context:
# Deploys from this branch will take these settings
# and override their current ones.
[context."staging/branch"]
    REACT_APP_BE_URL = https://didactlms-staging.herokuapp.com/api/

[context."master/branch"]
    REACT_APP_BE_URL = https://didactlms-staging.herokuapp.com/api/
